services:
  # Backend Application (Laravel)
  ma-backend:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: ma-backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
      - storage_data:/var/www/storage
    networks:
      - ma-network
    depends_on:
      - ma-db

  # Backend Nginx (serving Laravel)
  ma-nginx-backend:
    image: nginx:stable-alpine
    container_name: ma-nginx-backend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
      - storage_data:/var/www/storage
    networks:
      - ma-network
    depends_on:
      - ma-backend

  # Database
  ma-db:
    image: mysql:8.0
    container_name: ma-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ma_db_data:/var/lib/mysql
    networks:
      - ma-network

networks:
  ma-network:
    driver: bridge

volumes:
  storage_data:
    driver: local
  ma_db_data:
    driver: local
